// Writes server/.env with fresh random development keys. Safe to re-run: existing file is kept unless --force.
import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const serverRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const envFile = path.join(serverRoot, '.env');
const force = process.argv.includes('--force');

if (existsSync(envFile) && !force) {
  console.log(`server/.env already exists, leaving it alone (use --force to regenerate).`);
  process.exit(0);
}

const b64 = () => randomBytes(32).toString('base64');
const appPassword = randomBytes(18).toString('base64url'); // 24 characters
const keys = { k1: b64(), b1: b64() };
const storageDir = path.join(serverRoot, 'data', 'files');
mkdirSync(storageDir, { recursive: true });

const lines = [
  '# Development only. Generated by npm run init-dev. Never reuse these values elsewhere.',
  'NODE_ENV=development',
  'HOST=127.0.0.1',
  'PORT=4000',
  'PUBLIC_URL=http://localhost:4000',
  'TRUST_PROXY=false',
  '# Behind a public tunnel such as cloudflared (it connects from this computer): turn both on.',
  '# TRUST_PROXY=loopback makes the Hub use the real client address (also a comma separated list such as loopback, 172.29.10.2).',
  '# TUNNEL_HOOKS_ONLY=true makes the tunnel reach only the portal webhook receiver and the health check; everything else answers 404.',
  '# TRUST_PROXY=loopback',
  '# TUNNEL_HOOKS_ONLY=true',
  `DATABASE_URL=postgres://kph_app:${appPassword}@localhost:5433/kph`,
  'DATABASE_OWNER_URL=postgres://kph_owner:kph_owner_dev_password@localhost:5433/kph',
  `MASTER_KEYS='${JSON.stringify(keys)}'`,
  'ACTIVE_KEY_ID=k1',
  'BLIND_INDEX_KEY_ID=b1',
  'STORAGE_DRIVER=fs',
  `STORAGE_DIR=${storageDir}`,
  'SCANNER=none',
  'ALLOW_NO_SCANNER=true',
  'MAIL_FROM=Portal Hub <no-reply@localhost>',
  'SUPPORT_EMAIL=support@localhost',
  'PRIVACY_EMAIL=privacy@localhost',
  'SCRYPT_LOG_N=15',
  'DEMO_MODE=true',
  'PORTAL_FAKE=true',
  'RUN_WORKER=true',
  'SIGNUP_ENABLED=false',
  '# Two factor sign in is required for everyone. A Google sign in never skips the authenticator, so this can only be true.',
  'OIDC_REQUIRE_LOCAL_MFA=true',
];
writeFileSync(envFile, lines.join('\n') + '\n', { mode: 0o600 });
console.log('Wrote server/.env with fresh development keys.');
